// Code generated by ent, DO NOT EDIT.

package workout

import (
	"entgo.io/ent/dialect/sql"
	"github.com/MatiF100/Throw-Muffin-API/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Workout {
	return predicate.Workout(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Workout {
	return predicate.Workout(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Workout {
	return predicate.Workout(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Workout {
	return predicate.Workout(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Workout {
	return predicate.Workout(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Workout {
	return predicate.Workout(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Workout {
	return predicate.Workout(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Workout {
	return predicate.Workout(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Workout {
	return predicate.Workout(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.Workout {
	return predicate.Workout(sql.FieldEQ(FieldName, v))
}

// Intensity applies equality check predicate on the "Intensity" field. It's identical to IntensityEQ.
func Intensity(v int) predicate.Workout {
	return predicate.Workout(sql.FieldEQ(FieldIntensity, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.Workout {
	return predicate.Workout(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.Workout {
	return predicate.Workout(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.Workout {
	return predicate.Workout(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.Workout {
	return predicate.Workout(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.Workout {
	return predicate.Workout(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.Workout {
	return predicate.Workout(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.Workout {
	return predicate.Workout(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.Workout {
	return predicate.Workout(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.Workout {
	return predicate.Workout(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.Workout {
	return predicate.Workout(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.Workout {
	return predicate.Workout(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.Workout {
	return predicate.Workout(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.Workout {
	return predicate.Workout(sql.FieldContainsFold(FieldName, v))
}

// IntensityEQ applies the EQ predicate on the "Intensity" field.
func IntensityEQ(v int) predicate.Workout {
	return predicate.Workout(sql.FieldEQ(FieldIntensity, v))
}

// IntensityNEQ applies the NEQ predicate on the "Intensity" field.
func IntensityNEQ(v int) predicate.Workout {
	return predicate.Workout(sql.FieldNEQ(FieldIntensity, v))
}

// IntensityIn applies the In predicate on the "Intensity" field.
func IntensityIn(vs ...int) predicate.Workout {
	return predicate.Workout(sql.FieldIn(FieldIntensity, vs...))
}

// IntensityNotIn applies the NotIn predicate on the "Intensity" field.
func IntensityNotIn(vs ...int) predicate.Workout {
	return predicate.Workout(sql.FieldNotIn(FieldIntensity, vs...))
}

// IntensityGT applies the GT predicate on the "Intensity" field.
func IntensityGT(v int) predicate.Workout {
	return predicate.Workout(sql.FieldGT(FieldIntensity, v))
}

// IntensityGTE applies the GTE predicate on the "Intensity" field.
func IntensityGTE(v int) predicate.Workout {
	return predicate.Workout(sql.FieldGTE(FieldIntensity, v))
}

// IntensityLT applies the LT predicate on the "Intensity" field.
func IntensityLT(v int) predicate.Workout {
	return predicate.Workout(sql.FieldLT(FieldIntensity, v))
}

// IntensityLTE applies the LTE predicate on the "Intensity" field.
func IntensityLTE(v int) predicate.Workout {
	return predicate.Workout(sql.FieldLTE(FieldIntensity, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Workout) predicate.Workout {
	return predicate.Workout(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Workout) predicate.Workout {
	return predicate.Workout(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Workout) predicate.Workout {
	return predicate.Workout(sql.NotPredicates(p))
}
