// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/MatiF100/Throw-Muffin-API/ent/schema"
	"github.com/MatiF100/Throw-Muffin-API/ent/workout"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	workoutFields := schema.Workout{}.Fields()
	_ = workoutFields
	// workoutDescIntensity is the schema descriptor for Intensity field.
	workoutDescIntensity := workoutFields[1].Descriptor()
	// workout.DefaultIntensity holds the default value on creation for the Intensity field.
	workout.DefaultIntensity = workoutDescIntensity.Default.(int)
	// workout.IntensityValidator is a validator for the "Intensity" field. It is called by the builders before save.
	workout.IntensityValidator = workoutDescIntensity.Validators[0].(func(int) error)
}
